"""Add is_active column to medicines

Revision ID: dd693a89000f
Revises: 
Create Date: 2025-05-09 19:38:20.771507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd693a89000f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicines', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('medicines', 'entry_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medicines', 'entry_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('medicines', 'is_active')
    # ### end Alembic commands ###
